DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ServiceRequestStatus') THEN
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'MATCHED';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'PICKED_UP';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'EN_ROUTE';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
    ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
  END IF;
END $$;
